spring:
  profiles:
    active: dev #激活开发环境
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.myselftpro.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev  #开发环境
  application:
    name: microservice-product        #调用当前服务的服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5                 #数据库连接池的最小维持连接数
      initial-size: 5             #初始化连接数
      max-total: 5                #最大连接数
      max-wait-millis: 150        #等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:        #注册到哪个服务中心，多个中间用逗号隔开
      #      defaultZone: http://localhost:6001/eureka
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #microservice-product:8001
    prefer-ip-address: true  #访问路径就会显示为IP地址
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.myselftpro.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: prod  #生产环境
  application:
    name: microservice-product        #调用当前服务的服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123
    dbcp2:
      min-idle: 5                 #数据库连接池的最小维持连接数
      initial-size: 5             #初始化连接数
      max-total: 5                #最大连接数
      max-wait-millis: 150        #等待连接获取的最大超时时间
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:        #注册到哪个服务中心，多个中间用逗号隔开
      #      defaultZone: http://localhost:6001/eureka
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #microservice-product:8001
    prefer-ip-address: true  #访问路径就会显示为IP地址